/**
 * $POOP Token Configuration
 * Generated by setup-token script
 *
 * Network: Solana Devnet
 */

// Token mint address on Solana Devnet
export const TOKEN_MINT = '9Ak8bwDjYjs74ahqGcoQXhV8Z4msm9f5iKeYrZXf4ZtG';

// Reward pool wallet address
export const REWARD_POOL_ADDRESS = '7MjfcwHcTQiSKJykTARdCDx8Pu6sEMkNY7gq7nuXDoJU';

// Token decimals
export const TOKEN_DECIMALS = 9;

// Network
export const NETWORK = 'devnet';

// Reward pool keypair (for demo only - in production, use secure storage!)
// WARNING: Never expose private keys in production code
export const REWARD_POOL_KEYPAIR = [
  178, 87, 128, 50, 171, 235, 42, 71, 129, 144, 117, 196, 106, 163, 250, 67,
  137, 218, 124, 111, 203, 131, 155, 136, 83, 180, 78, 22, 83, 13, 150, 200,
  94, 117, 250, 236, 201, 107, 114, 174, 27, 124, 2, 139, 215, 90, 128, 242,
  58, 10, 172, 140, 151, 67, 209, 40, 61, 37, 113, 116, 0, 106, 36, 237
];
